### ISSUE TITLE
Add menu drawer to mobile and tablet views

### ISSUE THREAD

**Issue by sglangevin** [medic/cht-core#4332]
This ticket adds a menu drawer to the left side of the screen on tablet and mobile views. The menu drawer contains secondary navigation options (e.g. tour, about, user settings) as well as any pages that don't fit in the bottom navigation (e.g. reports or messages on mobile). It is accessed either by clicking on the hamburger menu or by swiping right and can be closed by clicking the X, clicking outside of the menu drawer, or swiping left.

## Menu drawer frame:
- [ ] Move the hamburger menu to the left side of the screen. It should be 24 x 24 px and have a 13px buffer on all sides.
- [ ] Menu drawer is 270px wide on all screen sizes and takes up the full vertical space.
- [ ] When the menu drawer is open, there is a transparent scrim covering the background, so the page underneath is partially visible.

## Header area with logo:
- [ ] Top header area is 224px tall, background color #4C5E66
- [ ] X is 24x24 px and has a 13px buffer on all sides (it should be in the exact same place as the hamburger menu icon was)
- [ ] Medic logo is located 20px in from the left edge and is 13px below the X. Medic logo is 230 x 70px.
- [ ] White text is located 20px below the Medic logo. The first line is H4 (16px) and bold and is displays the CHW's name (this is the name of the contact associated with the logged in user). The second line is H4 (16px) and regular weight - "Currently logged in"

## Sync status box:
- [ ] Sync status is located 20px below the second line of text. Sync status box is 270x70px.
- [ ] Icons before the first line of text are 12px from the top, 20px from the left edge and 24x24px in size.
- [ ] First line of text in the sync status box is H4 (16px) bold. It should have the same functionality as the existing app and can either say "All reports synced", "Currently syncing", or "Reports to sync". Text is green (#E8A727) unless it says "Reports to sync" in which case it changes to red (#DA2E1E). 
- [ ] The second line of text in the sync status box is H5 (14px) and regular weight. It lists the last sync time and is always dark gray (#333333).
- [ ] The bottom of the sync status box has a 3px colored line that is green (#7AB1B1) unless the status is "Reports to sync" in which case it changes to red (#DA2E1E).

## Pages/other:
- [ ] Icons for each page are 20px from left edge, 24x24px in size
- [ ] Page titles are 60px from left edge, H4 (16px) and gray (#333333)
- [ ] 1px gray line (#d3d3d3) separates the spillover pages (e.g. reports, messages, etc.) from the secondary navigation. It is 20px in from the left edge and 160px long.
- [ ] 1px gray line (#d3d3d3) separates the secondary navigation from the logout button. It is also 20px in from the left edge and 160px long. This line should not be there if the user doesn't have the logout option (disabled via permissions).

More information in the [design spec](https://docs.google.com/document/d/1GU3iWlnTz8H3WknnHVtPbMvWQpflUCeDPozk2Gm1Tx0/edit#heading=h.zczovwrlfce2).

![image](https://user-images.githubusercontent.com/1286381/37848581-ddbb213c-2e91-11e8-90a9-de3720226b36.png)

Blocked on #4323

**Comment by michaelkohn** [comment]
@n-orlowski anything worth keeping here or ok to close this? One notable thing here is the Medic logo in the drawer, if we wanted to keep some of the branding stuff, that might be a good place for us to put it.

**Comment by n-orlowski** [comment]
@michaelkohn ok to close, will take the branding consideration into the new designs :) thanks!
