### ISSUE TITLE
Replace floating action bars with floating action buttons

### ISSUE THREAD

**Issue by sglangevin** [medic/cht-core#4346]
Now that the main navigation is at the bottom of the screen, move some functions previously located there to floating action buttons (FABs). If images are needed for the FABs, those are available - [see this folder](https://drive.google.com/drive/folders/1PQ3Ydd3CyHToHXYnRx0oMPsTpkT3i3cv) and ping @amandacilek if you can't find what you need.

![image](https://user-images.githubusercontent.com/1286381/38000303-c6d493e8-31db-11e8-84f8-d36a34a89324.png)

## Mobile:
- [ ] Primary FAB appears on all people pages (people list as well as individual person & place profiles), the reports list page, the report detail page, and the messages page. It is a circle, 56x56px, periwinkle blue (#7092F5) with a white 24x24px icon in the center and is located 16px above the bottom nav and 16px from the right edge. All primary FABs have the + sign icon except for the one on the report detail page, which has the checkmark icon.
- [ ] Secondary FABs appear on person profile pages and the reports page. They are also a circle, white, 56x56px, with a 24x24px periwinkle blue icon (#7092F5) in the center. They are located 16px above the primary FAB and 16px from the right edge. On the person profile page, the icon is the message bubbles and on the reports page it is the checkbox icon.
- [ ] All FABs remain fixed as the user scrolls

## Tablet:
- [ ] Primary FAB appears on all person & place profile pages. It is a circle, 56x56px, periwinkle blue (#7092F5) with a white 24x24px + sign icon in the center and is located 16px above the bottom nav and 16px from the right edge of the card behind it.
- [ ] Primary FAB appears on the report detail page. It is a circle, 56x56px, periwinkle blue (#7092F5) with a white 24x24px checkmark icon in the center and is located 16px above the bottom nav and 16px from the right edge of the card behind it.
- [ ] Secondary FAB appears on all person profile pages. It is also a circle, white, 56x56px, with a 24x24px periwinkle blue message bubbles icon (#7092F5) in the center. It is located 16px above the primary FAB and 16px from the right edge of the card behind it.

## Desktop:
- [ ] Primary FAB appears on all person & place profile pages. It is a circle, 56x56px, periwinkle blue (#7092F5) with a white 24x24px + sign icon. Vertically, it is centered along the right edge of the top profile card and the top edge of the FAB is 133px from the top of the profile card.
- [ ] Primary FAB appears on the report detail page. It is a circle, 56x56px, periwinkle blue (#7092F5) with a white 24x24px checkmark icon. Vertically, it is centered along the right edge of the report detail card and the top edge of the FAB is 160px from the top of the report detail card.
- [ ] Secondary FAB appears on all person profile pages. It is also a circle, white, 56x56px, with a 24x24px periwinkle blue message bubbles icon (#7092F5) in the center. It is vertically centered along the right edge of the top profile card and located 16px above the primary FAB.

More information in [the design spec](https://docs.google.com/document/d/1GU3iWlnTz8H3WknnHVtPbMvWQpflUCeDPozk2Gm1Tx0/edit#bookmark=id.gwoymuj68wuo). Also consult Invision prototypes for more info on tablet & desktop views.

Blocked on #4323.

**Comment by garethbowen** [comment]
@latin-panda Can we close this as a dupe?

**Comment by latin-panda** [comment]
@n-orlowski can we close it?

**Comment by n-orlowski** [comment]
Yes please!

**Comment by garethbowen** [comment]
This is done!
