### ISSUE TITLE
Prototype for Documenting UI State - Contacts Page | List View (Access)

### ISSUE THREAD

**Issue by lorerod** [medic/cht-core#9397]
**Describe the issue**
We need to create documentation for the UI State by Config because the CHT has complex configurations that significantly impact how the user interface appears and functions. By documenting these configurations, we provide valuable guidance to the QA team to ensure they can accurately test the UI under various configurations. It also helps new team members quickly understand how the system is set up and how different configurations affect the UI. For first-time users, clear documentation makes navigating and using the tool easier, minimizing confusion and improving overall user experience.

This issue aims to prototype one feature (for the Contacts Page | List View (Access)) to identify unknowns and create a workflow for documenting UI States.

**Tasks already done**

- [X] Decide on the Feature:

We will use "Contacts Page - Access" as our first example.

- [X] Confirm Individual Scenarios:

We will use [this](https://docs.google.com/spreadsheets/d/1ucVVVVv7BR7C9AmTVgYm4H4OLSX2pmtXojvUElX00tc) list of scenarios required for the "Contacts Page - Access."

- [X] Design Configuration and Data:

Design the necessary configuration and data, including roles and names for households and other entities. We will start with [this](https://docs.google.com/spreadsheets/d/1ucVVVVv7BR7C9AmTVgYm4H4OLSX2pmtXojvUElX00tc). As part of this work, we will improve the design if needed.

**Tasks included in this issue**
- [ ] Create Tests for Screenshots:

    - [ ] Verify if existing end-to-end (e2e) tests cover the scenarios. If not, create new tests.

    - [ ] Update test data to be more realistic ("nice" data) if necessary for documentation purposes. If necessary, improve the design of the necessary configuration and data.

    - [ ] Run the tests to generate the required screenshots: Ensure the data and screenshots are consistent and realistic for documentation.

**Tasks not included in this issue**
- [ ] Draft Documentation Pages:

Begin drafting the page(s) for the cht-docs repository.
Include screenshots and detailed descriptions of each scenario.

- [ ] Deploy to Docs Site:

Manually deploy the updated documentation and screenshots to the docs site.
